### ISSUE TITLE
picture in picture

### ISSUE THREAD

**Issue by ericmersino** [Anonymousdog/displaycameras#100]
I have two feeds. I'm trying to run one full screen, with a second one overlapping that feed on the bottom right corner of the screen. Is there anyway to get this to work and stop flickering / glitching.
![Capture](https://user-images.githubusercontent.com/36427851/127765193-e0b62268-d4b9-44e1-bac2-804079ba0187.PNG)

**Comment by SvenVD** [comment]
This is not about displaycameras, but this can be done with showontop=true in Rpisurv https://gist.github.com/SvenVD/7b973cde2ce5dce6c8284606434e3a14

**Comment by ericmersino** [comment]
> This is not about displaycameras, but this can be done with showontop=true in Rpisurv https://gist.github.com/SvenVD/7b973cde2ce5dce6c8284606434e3a14

Thank you, I will check this out and report back

**Comment by Anonymousdog** [comment]
No. That would require a custom build with layer support added. I started
to get into that a bit in the layers branch but never completed the work.
If you look at the code, it should be pretty easy to hack together.

Andy
