### ISSUE TITLE
any option to blank screen at night and rewake in the morning

### ISSUE THREAD

**Issue by zeltak** [Anonymousdog/displaycameras#103]
**Is your feature request related to a problem? Please describe.**
Hi, was wondering if anyone knows or created a method to blank screen at night and re-awake at morning and can share with the community?

**Describe the solution you'd like**
an option to blank screen at night and re-awake at morning
**Describe alternatives you've considered**
tried using xset but that complains since i don't have a X session in place

**Comment by Anonymousdog** [comment]
That's outside the scope of this project, but it should be pretty simple to
do as a cron job (not integrated with this system per-se).

Andy

**Comment by jayjayseal** [comment]
This is very simple (though beyond this scope of project). I'm using the following setup.

Mind you i'm using this on a pi3. Whenever my homeautomations detect that no one is home i'll let it automatically SSh into the pi and execute the following line: **vcgencmd display_power 0** that disables the HDMI output and let's the screen go into sleep mode. Then do a **vcgencmd display_power 1** when person detection detects someone home again.

This works flawlessly every time and does not reaload the streams as it just disables the HDMI output and re enables it.

**Comment by zeltak** [comment]
wow @jayjayseal 

this is exactly what i was looking for

thx so much!

Z

**Comment by jayjayseal** [comment]
Your welcome :-)
