### ISSUE TITLE
Wont feed on boot

### ISSUE THREAD

**Issue by MajorDenkan** [Anonymousdog/displaycameras#104]
I really really think i have done everything right but still do not get ant feed.
I have tested to run OMX player and there i get the feed to work really good with no issues. 

i have attached the layout.conf
[layout.txt](https://github.com/Anonymousdog/displaycameras/files/7167667/layout.txt)

**Comment by Anonymousdog** [comment]
You have no feeds configured on the layout file.

**Comment by MajorDenkan** [comment]
i can see that i did not get the complete config file.. I have attached it now.
[layout.txt](https://github.com/Anonymousdog/displaycameras/files/7176031/layout.txt)

**Comment by Anonymousdog** [comment]
Missing a closing parethesis.

**Comment by MajorDenkan** [comment]
Where? As i can see i have a closing parantes after camera feeds...

**Comment by Anonymousdog** [comment]
No, you don't.  Put this, ), at the end of the file.

**Comment by Anonymousdog** [comment]
omxplayer deprecated in bullseye
