### ISSUE TITLE
displaycameras not working after upgrading to bullseye

### ISSUE THREAD

**Issue by vjiggi** [Anonymousdog/displaycameras#107]
**To Reproduce**
1. Install per README.md
2. Configure my feeds in layout.conf.default
3. Run 'sudo displaycameras start'
4. See error "..."

**Expected behavior**

**Screenshots**

**Raspberry Pi (please complete the following information):**
 - Hardware model: Raspberry Pi 3B+
 - OS: Raspbian_Lite Bullseye
 - Console: ssh
 - gpu memory split: default
 - displaycameras Version [ 0.8.3.3]

**Display Configuration
 - Display/Monitor resolution: [1920x1080]
 - Window matrix: [2x2]
 - Feed resolution: [720 x 480]

**Camera information (please complete the following information):**
 - Number of cameras: [4]
 - Camera models (if not Ubiquiti): Dahua rebranded
 - Managed

**Features enabled (please complete the following information):**
 - Rotation: [no]
 - Display Blanking: [no]
 - Display Detection: [no]

**NVR information (please complete the following information):**
 -  VIP Vision NVR

**Additional context**
stopped working after upgrading from buster to bullseye

`pi@raspberrypi:~ $ systemctl status displaycameras.service 
● displaycameras.service - Displays camera feeds for monitoring
     Loaded: loaded (/etc/systemd/system/displaycameras.service; enabled; vendor preset: enabled)
     Active: active (exited) since Sat 2021-11-20 17:49:15 AEDT; 13min ago
       Docs: man:systemd-sysv-generator(8)
    Process: 4295 ExecStart=/usr/bin/displaycameras start (code=exited, status=0/SUCCESS)
   Main PID: 4295 (code=exited, status=0/SUCCESS)
      Tasks: 1 (limit: 1169)
        CPU: 8.158s
     CGroup: /system.slice/displaycameras.service
             └─4316 dbus-daemon --fork --print-address 5 --print-pid 6 --session

Nov 20 17:49:10 raspberrypi displaycameras[4844]: Waiting for Backyard omxplayer startup 1
Nov 20 17:49:11 raspberrypi displaycameras[4844]: Waiting for Backyard omxplayer startup 2
Nov 20 17:49:12 raspberrypi displaycameras[4844]: Waiting for Backyard omxplayer startup 3
Nov 20 17:49:13 raspberrypi displaycameras[4844]: Waiting for Backyard omxplayer startup 4
Nov 20 17:49:15 raspberrypi displaycameras[4844]: Waiting for Backyard omxplayer startup 5
Nov 20 17:49:15 raspberrypi displaycameras[4844]: Backyard failed playback
Nov 20 17:49:15 raspberrypi displaycameras[4295]: Camera Display Started
Nov 20 17:49:15 raspberrypi displaycameras[4295]: For complete status info, run
Nov 20 17:49:15 raspberrypi displaycameras[4295]: /usr/bin/displaycameras status.
Nov 20 17:49:15 raspberrypi systemd[1]: Finished Displays camera feeds for monitoring.`

**Files
Attach any suspect config files.

**Comment by vjiggi** [comment]
It looks like omxplayer is not supported in bullsyeye

**Comment by Anonymousdog** [comment]
Yes, this pretty much deprecates this project unless I port it to VLC or
you run Stretch.

**Comment by vjiggi** [comment]
Reverted back to buster.
