### ISSUE TITLE
Differential layout rotation

### ISSUE THREAD

**Issue by LT-FoAmY** [Anonymousdog/displaycameras#11]
Forgive me if this is already possible, if that is the case I'm too stupid to work it out...
But is it / would it be possible to get differential layout rotation, as in have a 2x2 tile, that changes to a 1x1 of specific camera then rotates back to a 2x2 of multiple for example?
If this can already be done I'd appreciate an example layout.conf...

Thanks!

**Comment by mikestecker** [comment]
+1

I'd love to see this too. I have 5 cameras and I'd love to be able to put them on a grid all together, and then rotate to each one full screen individually, then back to the 4x4 grid or some other similar layout.
