### ISSUE TITLE
Can I access displaycamera output via my network?

### ISSUE THREAD

**Issue by guciopl** [Anonymousdog/displaycameras#111]
My alarm touch-panel supports displaying surveillance camera's stream but it has limitation to one camera per tab. I figured out that I can merge few feeds and build 2x2 display for my four cameras and present it as one stream. So here I am, with configured displaycameras application and judging from command line output it is working. Question is is it accessible via network so it can be set as another rtsp source, or it just merges outputs and present them to monitor connected to device on which it is running?

**Comment by Anonymousdog** [comment]
This is not supported at all. Displaycameras doe not combine streams. It
uses multiple instances of omxplayer to play as many streams as you
configure.

Sorry,
Andy
