### ISSUE TITLE
turn off/on screen by tapping on it

### ISSUE THREAD

**Issue by rventuri76** [Anonymousdog/displaycameras#17]
I do not want the screen to stay turned always on so I wrote following script (and make it a service) to turn on and off backlight screen on touch event.
This works with my 'official' raspberry 7' touch screen.
It also turn off the screen after some time.

Might be nice to integrate something like this and to see if it is possible to stop the steaming all together and not just the screen.

#!/bin/bash
loop_count=0
echo 'start'
while :
do timeout 0.2s evtest /dev/input/event0 > touchscreen_log.txt
        grep -q "type 1 (EV_KEY), code 330 (BTN_TOUCH), value 0" touchscreen_log.txt
        if (($?==0)) 
        then
                echo 'touch detected'
                power=$(cat /sys/class/backlight/rpi_backlight/bl_power)
                if (($power==0)) 
                then
                        echo 'turn off display backlight'
                        echo 1 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
                else
                        echo 'turn on display backlight'
                        loop_count=0
                        echo 0 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
                fi
                sleep 1
        fi
        loop_count=$[$loop_count+1]
        if (($loop_count>1000))
        then
                echo 'standby'
                loop_count=0
                echo 1 | sudo tee /sys/class/backlight/rpi_backlight/bl_power
        fi
done

**Comment by Anonymousdog** [comment]
This package is designed as a non-interactive service.  Neat add-on though.

To add service control, just add lines to stop and start the service 'systemctl start displaycameras' and 'systemctl stop displaycameras' to the relevant events (in addition to the screen backlight control).

**Comment by rventuri76** [comment]
Yes right. Why I din't think it bu myself ;-)
Thanks for the reply.
