### ISSUE TITLE
Odd issue with flickering

### ISSUE THREAD

**Issue by blimeybloke** [Anonymousdog/displaycameras#18]
This is odd.  I have rotation turned on, and using unifi with 7 cameras.  I am doing 4 per screen. 
 Everything loads correctly until its time to roate camera views, the feeds start flickering and overlaying each other.  I am using an older TV that is 1366x768 resolution.  Here is my window position:

For some reason hitting the code button on here is not formatting the text right so I attached a text file with my window_positions

I am sure this issue is me, but just looking for some assistance in case its a bug..
Cheers
[screen.txt](https://github.com/Anonymousdog/displaycameras/files/3268884/screen.txt)
[settings.txt](https://github.com/Anonymousdog/displaycameras/files/3268883/settings.txt)

Update:
I have tried master build and 8.3.3.3 and same flicker.  Its like its trying to decide which camera to rotate into each box because I can see 2 images if I look closely.

**Comment by jonathanelopez** [comment]
I had same issue today. Make sure you have your cameras named and listed.. Odd.. But fixed my issue.

**Comment by Anonymousdog** [comment]
Camera names are basically the index by which they accessed.  That's why the instructions stress that names are required.
