### ISSUE TITLE
Unable to do Screen Flop

### ISSUE THREAD

**Issue by jonathanelopez** [Anonymousdog/displaycameras#19]
**_Before filing a bug report_**

**Replicate your issue on Raspbian Lite**
Raspbian Lite is the preferred target OS for this system.  I will not address bugs that can only be replicated on 'nix with a graphical user interface.

**Ensure your operating system is up-to-date**
...and that you can replicate the problem with an up-to-date (and rebooted) system.
To ensure all is update, run the following in a terminal, `sudo apt-get update && sudo apt-get dist-upgrade -y && sudo apt-get auto-remove -y && sudo apt-get autoclean`

_**If you do the above two things and can still replicate the issue, then...**_

**Describe the bug**

**To Reproduce**
1. Install per README.md
2. Configure my feeds in layout.conf.default
3. Run 'sudo displaycameras start'
4. See error "..."

**Expected behavior**

**Screenshots**

**Raspberry Pi (please complete the following information):**
 - Hardware model Rasbery PI 3B+
 - OS: Raspbian_Lite Stretch
 - Console: ...
 - gpu memory split: 256MB
 - displaycameras Version 0.8.3.3

**Display Configuration
 - Display/Monitor resolution: 1920x1080
 - Window matrix: 1x2
 - Feed resolution: Low Res

**Camera information (please complete the following information):**
 - Number of cameras: [e.g. 6] 4
 - Camera models ReoLink
 - Managed/Unmanaged - Unmanaged

**Features enabled (please complete the following information):**
 - Rotation: Yes
 - Display Blanking: Yes
 - Display Detection: ? Yes - I believe so.

**NVR information (please complete the following information):**
 - NVR hardware: Amcrest NVR
 - NVR UniFi Video server version: N/A

**Additional context**
FYI very new with Rasberry PI. However having Issues with screen flop. I've tried editing the conf file I have screens rotating correctly. But would rather have them flop. I've read your readme file and cant seem to find the attribute to enable flop or even step. I've tried adding "seq_step=2" to layout.conf.default however that doesn't seem to work. 

Please help : (

**Files
Attach any suspect config files.

**Comment by Anonymousdog** [comment]
Duplicates #22
