### ISSUE TITLE
Find current installed version?

### ISSUE THREAD

**Issue by adutra22** [Anonymousdog/displaycameras#25]
Is there a command I can run to tell what the current installed version and/or committed version of DisplayCameras is currently installed on my RPI?

thanks,
Albert

**Comment by Anonymousdog** [comment]
This capability does not exist, but I'll add it soon.

**Comment by Anonymousdog** [comment]
FWIW, version numbers aren't incremented until I do a release.  Version number is listed in the main script.  You can find it with
`grep version /usr/bin/displaycameras`
