### ISSUE TITLE
Change resolution of larger tile

### ISSUE THREAD

**Issue by icepicknz** [Anonymousdog/displaycameras#26]
I currently have a 6 tile display with 1 offscreen for rotation. I'd love for the large (first window position) to be able to always load a higher quality stream.

window_positions=(
"0 0 1280 720" \
"1280 0 1920 360" \
"1280 360 1920 720" \
"1280 720 1920 1080" \
"640 720 1280 1080" \
"0 720 640 1080" \
"1920 600 2879 1199" \

Currently streams are _2 for lowest stream, _1 for mid quality and _0 for highest quality. I currently use _2 for all streams but the large screen is too low a quality so I'd love the ability to have it increase the quality for that tile when its rotated to

**Comment by Anonymousdog** [comment]
It's not practical due to delays in setting up at least two new playback sessions with each rotation. Rotation is currently achieved by moving already playing sessions from one screen position to another.  Loading a larger res stream would cause unacceptable delay.
