### ISSUE TITLE
Select camera feed for audio

### ISSUE THREAD

**Issue by gohamstergo** [Anonymousdog/displaycameras#27]
Would it be possible to add a section to the layout.conf to choose a feed to output audio via hdmi? Since the omxplayer code is universal in the 'displaycameras' file, there doesn't seem to be a way to choose just one.

Thanks!

**Comment by Anonymousdog** [comment]
Correct.  Code reuse and looping inherent to the function of the system means that I'd have to significantly refactor the code to accept arguments per-camera that aren't currently supported.  This feature is unlikely to be implemented (by me).

**Comment by gohamstergo** [comment]
ah ok, no worries.
