### ISSUE TITLE
Cannot do Screen Flop

### ISSUE THREAD

**Issue by stemccs** [Anonymousdog/displaycameras#29]
**_Before filing a bug report_**

**Replicate your issue on Raspbian Lite**
Raspbian Lite is the preferred target OS for this system.  I will not address bugs that can only be replicated on 'nix with a graphical user interface.
REPLICATED ON RASPBIAN 9.9
**Ensure your operating system is up-to-date**
...and that you can replicate the problem with an up-to-date (and rebooted) system.
To ensure all is update, run the following in a terminal, `sudo apt-get update && sudo apt-get dist-upgrade -y && sudo apt-get auto-remove -y && sudo apt-get autoclean`
DID ALL OF THIS AGAIN TO MAKE SURE
_**If you do the above two things and can still replicate the issue, then...**_

**Describe the bug**
A clear and concise description of what the bug is: 
Cannot do screen flop.
Thanks to your program, I am easily able to get 10 non-rotating feeds to display with no problems at all. I reconfigured my layout.conf.default file to 8 feeds--4 onscreen in a 2x2 matrix and 4 offscreen--in order to try your new screen flop feature. It will ONLY ROTATE IN SINGLE STEPS. I set the seq_step to 4 in the layout.conf.default file and also tried steps of 2 or 3, but all without any change. It only is able to rotate the 8 feeds into the screen in steps of 1.  The first offscreen feed becomes the bottom right feed, the bottom right becomes the bottom left, bottom left becomes top right, top right becomes top left and top left goes offscreen--all feeds step through the four positions only one step at a time, no matter whether seq_step=2 or 3 or 4.
I carefully read all of your resolved bugs to see if there was any advice for me there, and I did everything you recommended there, all to no avail. My ultimate goal is to flop two whole screens of 10 feeds each but first I need to made it work for two whole screens of 4 feeds each. PLEASE help me fix the seq_step feature.

**To Reproduce**
1. Install per README.md
2. Configure my feeds in layout.conf.default
3. Run 'sudo displaycameras start'
4. See error "..."
DONE
**Expected behavior**

**Screenshots**

**Raspberry Pi (please complete the following information):**
 - Hardware model: Canakit Raspberry Pi 3
 - OS: [e.g. Raspbian_Lite Stretch] Raspbian 9.9 Stretch
 - Console: [X-session/Pixel vs Text Console] text
 - gpu memory split: [e.g. 256MB] default
 - displaycameras Version [e.g. 0.8.3.3] 0.8.3.3

**Display Configuration
 - Display/Monitor resolution: [e.g., 1920x1080]  1024x768
 - Window matrix: [e.g. 2x2] 2x2
 - Feed resolution: [e.g., low-resolution or 640x360] low-res

**Camera information (please complete the following information):**
 - Number of cameras: [e.g. 6] 8
 - Camera models (if not Ubiquiti): Ubiquiti
 - Managed/Unmanaged: Managed

**Features enabled (please complete the following information):**
 - Rotation: [yes/no] yes
 - Display Blanking: [yes/no] no
 - Display Detection: [yes/no] no

**NVR information (please complete the following information):**
 - NVR hardware: virtual server
 - NVR UniFi Video server version: [e.g., 3.9.7] 5.10.25

**Additional context**

**Files
Attach any suspect config files.
I am attaching my layout.conf.default file but I had to add a .txt suffix or it would not upload. I do not have .txt on it when I run it, of course.
[layout.conf.default.txt](https://github.com/Anonymousdog/displaycameras/files/3584561/layout.conf.default.txt)

**Comment by Anonymousdog** [comment]
You have to use the development code (latest commits) to get the screen flop functionality.  Please see the README.md for instructions.
