### ISSUE TITLE
displaycameras.conf.1920x1200

### ISSUE THREAD

**Issue by MechX2** [Anonymousdog/displaycameras#4]
Any way we can get a default configuration file for monitors with a resolution of 1920x1200? Maybe a 6 camera setup.

**Comment by Anonymousdog** [comment]
16x9 feeds won't fit cleanly on a 16x10 monitor.  16x10 windows will distort the feeds but leave no black bars on sides of each window.  Which would you prefer (stretch or bars)?

**Comment by MechX2** [comment]
You the man! Stretch.

**Comment by Anonymousdog** [comment]
https://github.com/Anonymousdog/displaycameras/blob/master/example_layouts/layout.conf.1920x1200.6on4x4 rotates six feeds through a 2x2 matrix.  3x2 or 2x3 would be very distorted.  Recommend feeds no larger than the window size, 960x600.
