### ISSUE TITLE
Camera UDP rtsp stream

### ISSUE THREAD

**Issue by pezzotto** [Anonymousdog/displaycameras#45]
Hello and thanks for this great code.

I'm trying to create a display with two cheap Sricam but i noticed that the rtsp stream is UDP instead of TCP.

In fatc if i try sudo omxplayer --no-keys --no-osd --avdict rtsp_transport:**udp** <camera feed URL> --live -n -1 --timeout 30 
I have no problem to see the image.

There's a way to change the rtsp_transport in the code?

OR better.. a way to add a setting for single camera in the config if use tcp or udp?

Sorry maybe this is a pull request..

Thanks!

**Comment by theonemcdonald** [comment]
Every instance of omxplayer is spawned using the same base command, which uses TCP transport. You can change the transport mode in the code yourself...but again, this changes it for ALL streams spawned by the script

`	player="omxplayer --no-keys --no-osd --avdict **rtsp_transport:tcp** --win \"${window_positions[$x]}\" \"${camera_feeds[$i]}\" --live -n -1 --timeout "$omx_timeout" --dbus_name "org.mpris.MediaPlayer2.omxplayer.${camera_names[$i]}" >/dev/null &"`

**Comment by pezzotto** [comment]
Thank you i found it and changed, now it's ok.

The reason is that i have two Sricam that stream an rtsp only udp (strange i know)..
