### ISSUE TITLE
RTSP from Hikvision Cameras

### ISSUE THREAD

**Issue by jaruler17** [Anonymousdog/displaycameras#5]
Any idea why rtsp streams would not work from hikvision cameras. I have two other types that work fine. Verify the feed in VLC then put into the layout.conf.default as per other types of camera. Nothing comes up. Is there a specific setting the camera needs to be on for it to work in displaycameras? main and sub feed both not displaying. I dont get why they would work fine in VLC then not work in display cameras.

Ideas?

**Comment by jaruler17** [comment]
Are there restricted characters is the link? My password has a “+” in it.

**Comment by Anonymousdog** [comment]
Unsupported use case: won't fix.  Other users have problems with HikVision systems, especially with omxplayer maintaining a live feed; there MUST be something broken with these NVR RTSP feeds or the feeds the NVR gets from the cameras.

Use the debugging instructions in the README.md file (both to debug whatever escaping odd characters in the URL you need to do to pass your credentials in it AND to debug any other issues you might have with HikVision feeds).

**Comment by Anonymousdog** [comment]
This appears to be a known issue with omxplayer for some (yet undefined) combination of RTSP feeds or cameras and omxplayer, [https://github.com/popcornmix/omxplayer/issues/647]

**Comment by jkaa5522** [comment]
I know this is closed but I also had a similar issue until I used the sub stream feed. 

Main stream url:
rtsp://xxx:xxx@xx.xx.xx.xx/Streaming/Channels/101 (channel 1)
rtsp://xxx:xxx@xx.xx.xx.xx/Streaming/Channels/201 (channel 2)


Sub stream url:
rtsp://xxx:xxx@xx.xx.xx.xx/Streaming/Channels/102 (channel 1)
rtsp://xxx:xxx@xx.xx.xx.xx/Streaming/Channels/202 (channel 2)
