### ISSUE TITLE
lose HDMI for 2 specific rotations every time 

### ISSUE THREAD

**Issue by icepicknz** [Anonymousdog/displaycameras#50]
Hopefully someone knows this one or its something wrong with my layout for a quick easy fix.

I have 10 screens, every time the rotation gets to the last 10th screen I lose HDMI (no signal) for 30 seconds (2 rotations) and then it comes back. nothing in syslog, nothing high CPU that I can see, load average: 0.15, 0.21, 0.25

Window layout as follows
`"0 0 1280 720" \
"1280 0 1920 360" \
"1280 360 1920 720" \
"1280 720 1920 1080" \

#off-screen
"640 720 1280 1080" \
"0 720 640 1080" \
"1920 0 2560 360" \
"2560 0 3200 360" \
"3200 0 3840 360" \
"1920 360 2560 720" \
` 

You can view the layout at https://pasteboard.co/J7y8rLs.png

Anyone have any idea why it doesn't like that last rotation of 1920 360 2560 720?

**Comment by Anonymousdog** [comment]
Post your layout.default.conf (redacted) as an attachment, please.

My guess is you're running a higher-res feed (to start) in the large left
window.  That's going to cause problems as omxplayer has to down scale that
every time you move it to a smaller window (all the others).  Your windows
are overlapping by one pixel too (which makes them 641x361 which also
creates scaling duties for omxplayer).

Andy
