### ISSUE TITLE
Can you add the camera patrol function.Thank you very much for your dedication.

### ISSUE THREAD

**Issue by wjq8811** [Anonymousdog/displaycameras#51]

**Comment by Anonymousdog** [comment]
No idea what you mean by that.

**Comment by wjq8811** [comment]
With the 3x3 template, only 9 screens can be displayed. If there are 10 cameras, you can use one of them to display two cameras at the same time, and set it to switch once every 30 seconds. If there are 12 cameras, you can use 3 of them to display 2 cameras at the same time, and set 30 seconds to switch once.

I don't know if it can be expressed clearly.

**Comment by Anonymousdog** [comment]
The rotation loops and math were the hardest part of this to get working.
I don't know if it's even possible to do what you're asking without an
object oriented language.  RPi Surv is likely better suited for your
purposes.

**Comment by wjq8811** [comment]
well. Thank you very much. I wish you a happy life.
