### ISSUE TITLE
Image streaming

### ISSUE THREAD

**Issue by WirelessMind** [Anonymousdog/displaycameras#52]
Given the format of the two webcams, I have rotated the screen, but to cover the part with the shell, you will want to add a third fake webcam that transmits a black image.
Can I add streaming of an image?

![image](https://user-images.githubusercontent.com/18408814/82334003-b4eac000-99e7-11ea-83ad-93c98adb2da5.jpg)

**Comment by Anonymousdog** [comment]
No, you just use the screen blanking option right in the configuration
files.

**Comment by WirelessMind** [comment]
You are right! Sorry I didn't understand it was for that. My English is terrible!

**Comment by Anonymousdog** [comment]
No worries. Enjoy!
