### ISSUE TITLE
cant make it rotate

### ISSUE THREAD

**Issue by angelakied** [Anonymousdog/displaycameras#55]
hello, im trying to setup 2 cameras full screen 1920x1080  and rotate every 5 sec but after set it up the screen just turns off then back to the first camera, could you share me a working config

**Comment by Anonymousdog** [comment]
Use debug instructions to ensure you can play the second feed in omxplayer.

Next, use the template file, layout.conf.1920x1080.4on1x1, as the basis for
your layout config.  Remove camera names, windows and feed lines foe the
two feeds you won't need.

Thanks,
Andy
