### ISSUE TITLE
Rotate camera delay

### ISSUE THREAD

**Issue by misterfab31** [Anonymousdog/displaycameras#58]
Hi all,

I have 2 cameras on a same display, alternating 5 seconds each, which is the default

I would like to have one of the cameras for 20 seconds, and the other one for 5 seconds. 

I can't find a way to do this, is it possible?

**Comment by Anonymousdog** [comment]
Not part of the feature set and not expected as a feature improvement.

Sorry,
Andy

**Comment by misterfab31** [comment]
Thank you for your answer Andy.
It works fine like this anyway ;)
