### ISSUE TITLE
Broken RTSP camera feeds from Unifi Protect Beta '1.13.4-beta 2'

### ISSUE THREAD

**Issue by Crammy** [Anonymousdog/displaycameras#59]
Working solution to monitor cameras from Unifi Project stopped working.  After some testing found the issue to be related to the Unifi Protect Beta being used.  Prior to 1.13.4-beta 2 on Gen2+ NVR worked perfectly.  There is no downgrade path.

Since the update no more feeds, yet the feeds work ok on VLC.

This is not an issue with this code but highlighting the issue if used by others for the same reason.  Will advise on version changes from the Unifi Protect checking if the issue has been resolved.

Also reported here: [https://community.ui.com/questions/Tutorial-Raspberry-Pi-3-RTSP-Stream-Viewer/cc54f892-b8d6-46c5-81f3-ee58b9284889#answer/9b0ea0d7-8efc-4991-9d56-4d0e378fef0e](https://community.ui.com/questions/Tutorial-Raspberry-Pi-3-RTSP-Stream-Viewer/cc54f892-b8d6-46c5-81f3-ee58b9284889#answer/9b0ea0d7-8efc-4991-9d56-4d0e378fef0e)

**Comment by tdduarte** [comment]
new firmware just came out and it fixed this issue here.. just tested it
