### ISSUE TITLE
Layout Examples oddity

### ISSUE THREAD

**Issue by gohamstergo** [Anonymousdog/displaycameras#7]
I haven't looked at every example layout, but both:
layout.conf.1920x1080.3x3 and layout.conf.1920x1200.6on4x4

are commented as being: "# 2x2 screen with 3 off-screen windows." Could be just a labeling error, but just wanted to let you know.

**Comment by Anonymousdog** [comment]
I don't think either of those are in the actual release and we're just
one-offs created for specific users.

Andy

**Comment by Anonymousdog** [comment]
Fixed
