### ISSUE TITLE
Will this script work on a headless NUC running Buster 10.5?

### ISSUE THREAD

**Issue by tvmp** [Anonymousdog/displaycameras#70]
Just curious if this can work, given that Raspbian OS is based on Debian.
Anyone tried it? I don't want to test it as I'm quite a newbie with Linux and my current setup works as intended after a looooong time.

Alternatively, is there a way to run this inside Docker?

Thanks in advance

**Comment by Anonymousdog** [comment]
No, omxplayer is RPi specific.

**Comment by tvmp** [comment]
Thank you for your reply and for your amazing script, I am using it on an Rpi and was just cutious.
