### ISSUE TITLE
What about using vlc player instead of omxplayer?

### ISSUE THREAD

**Issue by akoryuerek** [Anonymousdog/displaycameras#74]

**Comment by Anonymousdog** [comment]
The future is vlc since omxplayer won't be in future releases of Raspbian
(IIRC), but I haven't done any of the work necessary to port this over to
vlc command line.

Andy

**Comment by jeremy-walker** [comment]
Just curious, do you have any plans on porting to VLC? 

I have a 21 camera setup and omxplayer refuses to work beyond 16 cameras. Up to 16 works absolutely fine. Starting the 17th feed, it keeps throwing `Failed to connect to TV service: -1`.
```
Starting omxplayer for cam17
tvservice-client: Failed to connect to TV service: -1
Waiting for cam17 omxplayer startup 0
Waiting for cam17 omxplayer startup 1
Waiting for cam17 omxplayer startup 2
Waiting for cam17 omxplayer startup 3
Waiting for cam17 omxplayer startup 4
Waiting for cam17 omxplayer startup 5
cam17 failed playback
```
I'm running Debian Buster (10.4) on a Raspberry Pi 3B with 512mb allocated towards GPU RAM. Even with the 16 feeds running, my main memory usage is at 25% which means it's not a memory issue. 

I'm wondering if this is a limitation with omxplayer.

**Comment by Anonymousdog** [comment]
Yes, this is covered elsewhere. This appears to be an omxplayer issue.

**Comment by jeremy-walker** [comment]
So, any chance you might consider porting displaycameras to vlc?

**Comment by SvenVD** [comment]
This is exactly what [Rpisurv 3](https://github.com/SvenVD/rpisurv/tree/v3_latest) is doing, Replaced omxplayer with vlc player.
