### ISSUE TITLE
Camera Rotation

### ISSUE THREAD

**Issue by IkaSGC** [Anonymousdog/displaycameras#76]
Hi, I'd like to ask about camera rotation. I'm trying to figure it out, but programming is new to me. I would like to make a rotation adjustment for a 6-camera scheme. It should work so that the cameras in the minimized windows are static. After a certain time, all 5 cameras would rotate in the enlarged window. The scheme would be with 6 windows, but there would be only five cameras. Instead of the sixth, all the cameras would take rotation. How to do it?

**Comment by Anonymousdog** [comment]
I have no idea. It was difficult getting the current rotation to work
without an object oriented language. RPiSurv may do what you want.

Thanks
