### ISSUE TITLE
High Resolution doesn't Show

### ISSUE THREAD

**Issue by monza258** [Anonymousdog/displaycameras#79]
Hi, is there a Problem to stream High Quality Streams?
I have a 3 Pixel camera with to Streams. 

like:
**First Stream**
rtsp://192.168.0.111:554/11
Resolution:2304x1296
Bit rate:1535

**Second stream**
rtsp://192.168.0.111:554/12
Resolution:640x352
Bit rate:1024

I can't use the First Stream in displaycameras. When I us I get a blank screen. 
Second Stream is bad Quality and I can't change the Resolution in Camera Settings. 

Is there any way to show the First Stream in displaycameras?
Can i fange any settings in pi to show the First Stream?

Hardware 
PI4 2GB

**Comment by Anonymousdog** [comment]
These hi res streams have not been tested, but, if omxplayer can display
them, they should work with the package (which is just scripts that manage
omxplayer instances).

Andy
