### ISSUE TITLE
Unable to set rotate order

### ISSUE THREAD

**Issue by MelvinRC** [Anonymousdog/displaycameras#80]
Maybe I'm doing something wrong, but cannot find anything to set the rotate order in this great script.

For example; I have 4 camera's (frontleft frontmiddle front right back)
The rotation now goes from frontleft -> frontmiddle -> back -> frontright -> frontleft and so on.

How can I change that to frontleft -> frontmiddle -> frontright -> back -> frontleft...?

Hope that there is an answer for this question :-)
Thanks in advance!

**Comment by Anonymousdog** [comment]
They are displayed in an order that is basically a cascade in the order
your windows are configured. Changing the window configuration order would
change the sequence.
