### ISSUE TITLE
Proposal for ReadMe

### ISSUE THREAD

**Issue by 19dexter86** [Anonymousdog/displaycameras#81]
The camera names must start with a letter. If the cameras are titled with a number the stream will not run. Error message: dbus_bus_request_name was incorrect.

I searched for a long time for the solution and thought this would help others.

Best greetings

**Comment by Anonymousdog** [comment]
This information is already present in the README.md file,
"!!!WARNING!!!

Camera Names must conform to DBUS namespace restrictions: valid UTF-8 only
containing the ASCII characters "[A-Z][a-z][0-9]_" and must not begin with
a digit or dot/period/"."

!!!WARNING!!!"
