### ISSUE TITLE
Screen Rotate

### ISSUE THREAD

**Issue by sjacksier** [Anonymousdog/displaycameras#83]
Is it possible to have it rotate multiple screens at a time? Like if you have 2x2 and 8 camera feeds, you display cameras 1-4 for some time, then 5-8. I can have it do 1-4, then 2-5, then 3-7 etc but not scroll multiple at a time.

**Comment by Anonymousdog** [comment]
Add ' seq_step=4' on its own line somewhere in your layout.conf.default or
displaycameras.conf files
