### ISSUE TITLE
1x3 vertical 

### ISSUE THREAD

**Issue by akoryuerek** [Anonymousdog/displaycameras#88]
Hi Guys. I have a problem with the1x3 portrait mode setup. Sometimes one stream disappears and comes back again after couple of seconds. Has anyone tips for optimization?

Rasp pi4 2gb
display rotation in /boot/config.txt
600mb gpu
all 3 streams are 1080p

config

windows=(window0 window1 window2)
window_positions=(""0 0 1080 640" "0 640 1080 1280" "0 1280 1080 1920"")
camera_names=(X1 X4 X2)
camera_feeds=("rtsp://192.168.1.220/x/1" "rtsp://192.168.1.220/x/4" "rtsp://192.168.1.220/x/2")

**Comment by Anonymousdog** [comment]
I would use much smaller resolution feeds than 1080p. All three of those feeds are being downscaled to display...bad juju.
The windows positions should have one less pixel in each dimension (e.g., "0 0 1079 639")...this is a very minor issue but can cause problems if your feeds are exactly 1080 wide or 640 high, and the one additional pixel forces upscaling.
