### ISSUE TITLE
Button + timer

### ISSUE THREAD

**Issue by jelloo8** [Anonymousdog/displaycameras#96]
I want to add a button so I can turn on the display and a timer to turn off the screen after a couple of minutes. Does someone know how to add that to the program? Or is there a way to turn on the screen when montion is detected on the camera? 

Thanks!!

**Comment by Anonymousdog** [comment]
Both items are out of scope for this project. I bet the hardware button to
turn on screen (and timer to turn off) is a project that exists somewhere.

Andy
