### ISSUE TITLE
Camera rotate fix position

### ISSUE THREAD

**Issue by daendaen** [Anonymousdog/displaycameras#97]
Hi and thanks for your project.

Maybe someone can help me with the my problem?

I have 6 cameras. the 2x2 view is configured and working.
I would like to see cameras 1 + 2 always, only cameras 3 + 4 should be integrated into the rotation. is that possible?
it is a bit confusing when all cameras always rotate in a circle.

**Comment by Anonymousdog** [comment]
With current code, you can't set any cameras as fixed but you can set
seq_step to 4 to get a fresh set of cameras on each rotation. It's not
ideal, but it's what we have as of now.

RPiSurv may well serve you better if you have "advanced needs" like this
and no need for the ultra light weight of displaycameras.

Thanks,
Andy
