### ISSUE TITLE
Rotate groups of cameras into view at once

### ISSUE THREAD

**Issue by JGVB** [Anonymousdog/displaycameras#98]
Instead of rotating one camera into view, is there/could there be a way to have cameras 1,2,3,4 on screen replaced by 5,6,7,8 all at once?

**Comment by Anonymousdog** [comment]
From the READEME.md,"Rotation stepping (new - alpha feature)

To rotate more aggressively than one feed at a time, set in the applicable
layout.conf.* file "seq_step" to a integer between 1 and the number of
cameras that fit on screen at any one time.
<https://github.com/Anonymousdog/displaycameras#screen-flop-new---alpha-feature>Screen
"Flop" (new - alpha feature)

If you want rotation to show you a full screen of feeds, then show you as
many as possible that were off screen, and so on until it goes back to the
original set (i.e., "flopping" between unique screen-fulls of feeds), set
"seq_step" equal to the number of cameras that fit on screen at one time."
